import pygal
from pygal.style import DefaultStyle
import pandas as pd
from typing import List, Dict, Optional, Union
import re
import os

class PygalVisualizer:
    def __init__(self, dataframe: pd.DataFrame):
        """
        Initialize with a pandas DataFrame
        
        Args:
            dataframe: Input data for visualization
        """
        self.df = dataframe
        self._style = DefaultStyle
        self._valid_charts = {
            'Bar', 'HorizontalBar', 'Line', 'Histogram', 
            'Pie', 'Scatter', 'StackedBar', 'Dot'
        }
        
    def set_style(self, style_name: str) -> None:
        """
        Change Pygal visualization style
        
        Args:
            style_name: Pygal style class name (e.g., 'DarkStyle', 'LightSolarizedStyle')
        """
        try:
            self._style = getattr(pygal.style, style_name)
        except AttributeError:
            raise ValueError(f"Invalid style. Available: {dir(pygal.style)}")

    def generate_visualization(
        self,
        question: str,
        output_path: str,
        columns: Optional[List[str]] = None,
        chart_type: Optional[str] = None,
        **chart_args
    ) -> Dict[str, Union[str, bool]]:
        """
        Generate and execute Pygal visualization
        
        Args:
            question: Analysis question/objective
            output_path: Where to save SVG (e.g., 'output/chart.svg')
            columns: Specific columns to visualize (auto-detected if None)
            chart_type: Force specific chart type (auto-detected if None)
            chart_args: Additional chart configuration
            
        Returns:
            Dictionary with:
            - 'code': Generated Python code
            - 'success': Execution status
            - 'message': Additional info
        """
        # Create output directory if needed
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        try:
            # Generate the Pygal code
            pygal_code = self._generate_pygal_code(
                question=question,
                output_path=output_path,
                columns=columns,
                chart_type=chart_type,
                **chart_args
            )
            
            # Execute the code
            exec_env = {
                'data_source': self.df,
                'pygal': pygal,
                'pd': pd,
                'self': self 
            }
            print(pygal_code)
            exec(pygal_code, exec_env)
            
            return {
                'code': pygal_code,
                'success': True,
                'message': f"SVG saved to {output_path}",
                'output_path': output_path
            }
            
        except Exception as e:
            return {
                'code': pygal_code if 'pygal_code' in locals() else '',
                'success': False,
                'message': f"Error: {str(e)}"
            }

    def _generate_pygal_code(
        self,
        question: str,
        output_path: str,
        columns: Optional[List[str]] = None,
        chart_type: Optional[str] = None,
        **chart_args
    ) -> str:
        """
        Core code generation logic
        """
        # Auto-detect columns if not specified
        if not columns:
            columns = self._auto_detect_columns(question)
        columns = self._validate_columns(columns)
        
        # Determine chart type
        if not chart_type:
            chart_type = self._determine_chart_type(question, columns)
        chart_type = self._validate_chart_type(chart_type)
        
        # Generate code components
        data_code, x_labels = self._generate_data_code(chart_type, columns)
        config_code = self._generate_config_code(chart_args)
        series_code = self._generate_series_code(chart_type, columns)
        
        # Build full code template
        return f"""# PYTHON CODE GENERATED BY PygalVisualizer
import pygal
import pandas as pd

# DATA PREPARATION
df = data_source  # Input DataFrame reference
{data_code}
{x_labels}

# CHART CONFIGURATION
{config_code}

# CHART CREATION
chart = pygal.{chart_type}(config)
chart.title = {repr(self._clean_title(question))}

# DATA SERIES
{series_code}

# OUTPUT
chart.render_to_file({repr(output_path)})
"""

    def _auto_detect_columns(self, question: str) -> List[str]:
        """Heuristics to select relevant columns based on question"""
        # Simple implementation - can be enhanced with NLP
        numeric_cols = [col for col in self.df.columns 
                       if pd.api.types.is_numeric_dtype(self.df[col])]
        
        if "distribution" in question.lower() and numeric_cols:
            return [numeric_cols[0]]  # Default to first numeric column
        return [self.df.columns[0]]  # Fallback to first column

    def _validate_columns(self, columns: List[str]) -> List[str]:
        """Ensure columns exist in DataFrame"""
        invalid = [col for col in columns if col not in self.df.columns]
        if invalid:
            raise ValueError(f"Columns not found: {invalid}")
        return columns

    def _validate_chart_type(self, chart_type: str) -> str:
        """Ensure requested chart type is supported"""
        if chart_type not in self._valid_charts:
            raise ValueError(f"Invalid chart type. Choose from: {self._valid_charts}")
        return chart_type

    def _determine_chart_type(self, question: str, columns: List[str]) -> str:
        """Smart chart type selection based on data and question"""
        col_types = [pd.api.types.is_numeric_dtype(self.df[col]) for col in columns]
        
        # Question keywords
        q = question.lower()
        if "distribution" in q:
            return "Histogram" if all(col_types) else "Bar"
        elif "relationship" in q and len(columns) >= 2:
            return "Scatter" if all(col_types) else "StackedBar"
        elif "trend" in q and len(columns) >= 2:
            return "Line"
        elif "composition" in q:
            return "Pie"
        return "Bar"  # Default

    def _generate_data_code(self, chart_type: str, columns: List[str]) -> tuple:
        """Generate data preparation code based on chart type"""
        if chart_type == "Histogram":
            return (
                f"data = pd.cut(df['{columns[0]}'], bins=10).value_counts().sort_index()",
                "x_labels = [str(interval) for interval in data.index]"
            )
        elif chart_type == "Bar":
            return (
                f"data = df['{columns[0]}'].value_counts().sort_values(ascending=False)",
                "x_labels = data.index.astype(str).tolist()"
            )
        elif chart_type == "Pie":
            return (
                f"data = df['{columns[0]}'].value_counts()",
                "x_labels = data.index.astype(str).tolist()"
            )
        else:
            return (
                f"data = df[{columns}]",
                ""
            )

    def _generate_config_code(self, chart_args: dict) -> str:
        """Generate chart configuration code"""
        defaults = {
            'style': self._style.__name__,  # Use the style class name
            'x_label_rotation': 45,
            'truncate_label': 15,
            'show_legend': True,
            'tooltip_border_radius': 10
        }
        defaults.update(chart_args)
        
        config_items = []
        for k, v in defaults.items():
            if k == 'style':
                config_items.append(f"style=pygal.style.{v}")  # Reference style properly
            elif isinstance(v, bool):
                config_items.append(f"{k}={v}")
            else:
                config_items.append(f"{k}={repr(v)}")
        
        return f"config = pygal.Config(\n    {',\n    '.join(config_items)}\n)"
    def _generate_series_code(self, chart_type: str, columns: List[str]) -> str:
        """Generate data series addition code"""
        if chart_type in ["Scatter", "Line"]:
            return '\n'.join(f"chart.add('{col}', df['{col}'].tolist())" 
                            for col in columns)
        elif chart_type in ["Bar", "Histogram", "Pie"]:
            return "chart.add('Distribution', data.values)"
        elif chart_type == "StackedBar":
            return '\n'.join(f"chart.add('{col}', df['{col}'].value_counts())" 
                            for col in columns)
        return ""

    def _clean_title(self, text: str) -> str:
        """Clean and truncate chart title"""
        text = re.sub(r'[^\w\s-]', '', text.strip())[:60]
        return text + ('...' if len(text) >= 60 else '')