 # PYTHON CODE GENERATED BY PygalVisualizer
import pygal
import pandas as pd
data_source = pd.read_csv('sales.csv')
# DATA PREPARATION
df = data_source  # Input DataFrame reference
data = df[['sales', 'orderdate_year']]

x_labels = df['orderdate_month'].astype(str)

# CHART CONFIGURATION
config = pygal.Config(
    style=pygal.style.DarkSolarizedStyle,
    x_label_rotation=45,
    truncate_label=15,
    show_legend=True,
    tooltip_border_radius=10,
    width=1200,
    height=800
)

# CHART CREATION
chart = pygal.Line(config)
chart.title = 'Sales by Month'
chart.x_labels = x_labels  # Set the x-axis labels

# DATA SERIES - only sales as y-values
chart.add('Sales', df['sales'].tolist())
