import pygal
from pygal.style import DefaultStyle
import pandas as pd
from typing import List, Dict, Optional, Union
import re
import os

class Visualizer:
    def __init__(self, dataframe: pd.DataFrame):
        """
        Initialize with a pandas DataFrame
        
        Args:
            dataframe: Input data for visualization
        """
        self.df = dataframe
        self._style = DefaultStyle
        self._valid_charts = {
            'Bar', 'HorizontalBar', 'Line', 'Histogram', 
            'Pie', 'XY', 'StackedBar', 'Dot'  # Changed 'Scatter' to 'XY'
        }
        
    def set_style(self, style_name: str) -> None:
        """
        Change Pygal visualization style
        
        Args:
            style_name: Pygal style class name (e.g., 'DarkStyle', 'LightSolarizedStyle')
        """
        try:
            self._style = getattr(pygal.style, style_name)
        except AttributeError:
            raise ValueError(f"Invalid style. Available: {dir(pygal.style)}")

    def generate_visualization(
        self,
        question: str,
        output_path: str,
        columns: List[str],
        chart_type: str,
        **chart_args
    ) -> Dict[str, Union[str, bool]]:
        """
        Generate and execute Pygal visualization
        
        Args:
            question: Chart title/description
            output_path: Where to save SVG (e.g., 'output/chart.svg')
            columns: List of columns to visualize
            chart_type: Type of chart to generate
            chart_args: Additional chart configuration
            
        Returns:
            Dictionary with:
            - 'code': Generated Python code
            - 'success': Execution status
            - 'message': Additional info
        """
        # Create output directory if needed
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Add XY-specific validation
        if chart_type == "XY" and len(columns) != 2:
            return {
                'success': False,
                'message': "XY chart requires exactly 2 columns (x and y)"
            }
            
        try:
            # Generate the Pygal code
            pygal_code = self._generate_pygal_code(
                question=question,
                output_path=output_path,
                columns=columns,
                chart_type=chart_type,
                **chart_args
            )
            
            # Execute the code
            exec_env = {
                'data_source': self.df,
                'pygal': pygal,
                'pd': pd,
                'self': self 
            }
            print(pygal_code)
            exec(pygal_code, exec_env)
            
            return {
                'code': pygal_code,
                'success': True,
                'message': f"SVG saved to {output_path}",
                'output_path': output_path
            }
            
        except Exception as e:
            return {
                'code': pygal_code if 'pygal_code' in locals() else '',
                'success': False,
                'message': f"Error: {str(e)}"
            }

    def _generate_pygal_code(
        self,
        question: str,
        output_path: str,
        columns: List[str],
        chart_type: str,
        **chart_args
    ) -> str:
        """
        Core code generation logic
        """
        # Validate inputs
        self._validate_columns(columns)
        self._validate_chart_type(chart_type)
        
        # Generate code components
        data_code, x_labels = self._generate_data_code(chart_type, columns)
        config_code = self._generate_config_code(chart_args)
        series_code = self._generate_series_code(chart_type, columns)
        
        # Build full code template
        return f"""# PYTHON CODE GENERATED BY PygalVisualizer
import pygal
import pandas as pd

# DATA PREPARATION
df = data_source  # Input DataFrame reference
{data_code}
{x_labels}

# CHART CONFIGURATION
{config_code}

# CHART CREATION
chart = pygal.{chart_type}(config)
chart.title = {repr(self._clean_title(question))}

# DATA SERIES
{series_code}

# OUTPUT
chart.render_to_file({repr(output_path)})
"""

    def _validate_columns(self, columns: List[str]) -> None:
        """Ensure columns exist in DataFrame"""
        invalid = [col for col in columns if col not in self.df.columns]
        if invalid:
            raise ValueError(f"Columns not found: {invalid}")

    def _validate_chart_type(self, chart_type: str) -> None:
        """Ensure requested chart type is supported"""
        if chart_type not in self._valid_charts:
            raise ValueError(f"Invalid chart type. Choose from: {self._valid_charts}")

    def _generate_data_code(self, chart_type: str, columns: List[str]) -> tuple:
        """Generate data preparation code based on chart type"""
        if chart_type == "Histogram":
            return (
                f"data = df['{columns[0]}'].value_counts().sort_index()",
                "x_labels = [str(interval) for interval in data.index]"
            )
        elif chart_type in ["Bar", "Pie"]:
            return (
                f"data = df['{columns[0]}'].value_counts().sort_values(ascending=False)",
                "x_labels = data.index.astype(str).tolist()"
            )
        else:
            return (
                f"data = df[{columns}]",
                ""
            )

    def _generate_config_code(self, chart_args: dict) -> str:
        """Generate chart configuration code"""
        defaults = {
            'style': self._style.__name__,
            'x_label_rotation': 45,
            'truncate_label': 15,
            'show_legend': True,
            'tooltip_border_radius': 10
        }
        defaults.update(chart_args)
        
        config_items = []
        for k, v in defaults.items():
            if k == 'style':
                config_items.append(f"style=pygal.style.{v}")
            elif isinstance(v, bool):
                config_items.append(f"{k}={v}")
            else:
                config_items.append(f"{k}={repr(v)}")
        
        return f"config = pygal.Config(\n    {',\n    '.join(config_items)}\n)"

    def _generate_series_code(self, chart_type: str, columns: List[str]) -> str:
        """Generate data series addition code"""
        if chart_type == "XY":
            if len(columns) != 2:
                raise ValueError("XY chart requires exactly 2 columns (x and y)")
            x_col, y_col = columns
            return f"chart.add('XY Data', list(zip(df['{x_col}'], df['{y_col}'])))"
        elif chart_type == "Line":
            return '\n'.join(f"chart.add('{col}', df['{col}'].tolist())" 
                            for col in columns)
        elif chart_type in ["Bar", "Histogram", "Pie"]:
            return "chart.add('Distribution', data.values)"
        elif chart_type == "StackedBar":
            return '\n'.join(f"chart.add('{col}', df['{col}'].value_counts())" 
                            for col in columns)
        return ""

    def _clean_title(self, text: str) -> str:
        """Clean and truncate chart title"""
        text = re.sub(r'[^\w\s-]', '', text.strip())[:60]
        return text + ('...' if len(text) >= 60 else '')